(part "CSD88537ND"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "S1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "G1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "S2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "G2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "D2_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "D2_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "D1_1") (portType INOUT))
        (port "8" (symbPinId 8) (portName "D1_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "CSD88537ND")
    (property "Mouser_Part_Number" "595-CSD88537ND")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/CSD88537ND?qs=7wMBv%2Ftbz9KkQ3rfcHocDA%3D%3D")
    (property "Arrow_Part_Number" "CSD88537ND")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/csd88537nd/texas-instruments?region=nac")
    (property "Description" "60-V Dual N-Channel NexFET Power MOSFET, CSD88537ND")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/csd88537nd")
    (property "symbolName1" "CSD88537ND")
)
